env:
  browser: true
  es2021: true
  node: true
extends:
  - '@swimlane/eslint-config/typescript'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parserOptions:
  ecmaVersion: 12
  sourceType: module