name: Lint

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run test:lint

    - name: Run Prettier
      run: npm run test:prettier